### ISSUE TITLE
Preserve Yaml structure

### ISSUE THREAD

**Issue by TenKenZero** [TextQLLabs/dbt-doc-py#3]
Currently, the application is changing the order of the YAML file's content when it introduces the description block.

This is the original YAML file:
![issue3-1](https://github.com/TextQLLabs/dbt-doc-py/assets/11514837/2b3ab65a-b4b0-41bf-9d2e-4bae597062f2)

This is the modified YAML with the documentation generated by the app:
![issue3-2](https://github.com/TextQLLabs/dbt-doc-py/assets/11514837/8dcc62df-44ec-4ae1-a955-808c79cabc25)

We need to add the `description` section after the `name` one and keep the other sections in the same order they had before running the app.

**Comment by munish7771** [comment]
Looks like an issue with yaml.safe_load() call to read yaml file into python dict.

There are two possible resolutions here - 
1. use yaml.load(), which preserves the order in yaml file. But should not be used with untrusted data.
2. creating own implementation of yaml.safe_load to preserve the order of yaml file.

Going with the 2nd approach as it looks safe.

**Comment by munish7771** [comment]
So, the issue was while writing to yaml file. Introduced a new dependency `ruamel.yaml` just for write.

`ruamel.yaml` - to write to yaml file, preserves the order of keys.
`PyYaml` - to read the yaml file (existing flow). Wanted to remove this and use `ruamel.yaml` but don't feel confident since there are no test cases to validate.

**Comment by TenKenZero** [comment]
Yes!
I'll do
